import type { Metadata } from "next";
import "./globals.css";




export const metadata: Metadata = {
  title: "Blog Avelar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BA" className="dark">
      <body>{children}</body>
    </html>
  );
}
